AppKu/urls.py
from django.urls import path
from . import views

app_name = 'AppKu'

urlpatterns = [
    path('', views.home,name='home'),
    path('profile/', views.profile, name='profile'),
    path('contact/', views.contact, name='contact'),
    path('seeMore/', views.seeMore, name='seeMore'),
    path('schedule/', views.schedule, name='schedule'),
    path('schedule/create', views.schedule_create, name='schedule_create'),
    path('schedule/clear/<int:id>/', views.schedule_delete, name='schedule_delete'),

    ]

ProjectKu/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('AppKu.urls')),
]

AppKu/models.py
from django.db import models
from datetime import datetime

# Create your models here.


class Schedule(models.Model):

    activity = models.CharField(max_length=30)
    date = models.DateTimeField(default=datetime.now)
    time = models.TimeField()
    place = models.CharField(max_length=20)
    category = models.CharField(max_length=20)

#   def __str__(self):
 #       return self.activity

AppKu/forms.py
from django import forms
from .models import Schedule


class ScheduleForm(forms.ModelForm):
    class Meta:
        model = Schedule
        fields = ['activity', 'date', 'time', 'place', 'category']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
            'time': forms.TimeInput(attrs={'type': 'time'})}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

AppKu/views.py
from django.shortcuts import render
from . import models
from.models import Schedule
from . import forms
from django.shortcuts import redirect
from django.http import HttpResponse

# Create your views here.
def home(request):
    return render(request, 'home.html')

def profile(request):
    return render(request, 'profile.html')

def contact(request):
    return render(request, 'contact.html')

def seeMore(request):
    return render(request, 'seeMore.html')

def schedule(request):
    schedules = Schedule.objects.all().order_by('date')
    return render(request, 'schedule.html', {'schedules': schedules})

def schedule_create(request):
    if request.method == 'POST':
        form = forms.ScheduleForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/schedule')

    else:
        form = forms.ScheduleForm()
    return render(request, 'schedule_create.html', {'form': form})

def schedule_delete(request, id):
    if request.method == 'POST':
        Schedule.objects.filter(id=id).delete()
        return redirect('AppKu:schedule')
    else:
        return HttpResponse("/GET not allowed")

AppKu/templates/contact.html
<!doctype html>
<html lang="en">
{% load static %}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/cssKu.css' %}">
    <title>My Website</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light background-color: #fffff; ">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse navbar-center" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/profile">About Me</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/contact">Contact</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/schedule">My Schedule</a>
            </li>
        </ul>
    </div>
</nav>

<div class="row contact">
    <img src="{% static 'images/contact.png' %}">
</div>
<div class="row">
    <div class= "col-md-3 mail">
        <img src="{% static 'images/mail.png' %}">
    </div>
    <div class="col-md-3 email">
        <p>hana.fadhila@ui.ac.id</p>
    </div>
    <div class="col-md-3 wa">
        <img src="{% static 'images/whatsapp.png' %}">
    </div>
    <div class="col-md-3 whatsapp">
        <p>+6285691683705</p>
    </div>
</div>
<div class="row">
    <div class="col-md-12 blank"></div>
</div>
<div class="row">
    <div class="col-md-3 link"> <a href='https://www.linkedin.com/in/hana-fadhila-ardiansyah-24ba0017b/?originalSubdomain=id'>
        <img src="{% static 'images/linkedin.png' %}"></a>
    </div>
    <div class="col-md-3 linkedin">
        <p> Hana Fadhila Ardiansyah</p>
    </div>
    <div class="col-md-3 insta">
        <a href='https://www.instagram.com/hanardiansyah/?hl=en'>
            <img src="{% static 'images/instagram.png' %}"></a>
    </div>
    <div class="col-md-3 instagram">
        <p>Hana Fadhila Ardiansyah</p>
    </div>
</div>
<div class="row">
    <div class="col-md-12 blank"></div>
</div>
<div class="row">
    <div class = "col-md-3 one">
    </div>
    <div class = "col-md-3 two">
    </div>
    <div class = "col-md-3 three">
    </div>
    <div class = "col-md-3 four">
    </div>
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

AppKu/templates/home.html
<!doctype html>
<html lang="en">
{% load static %}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/cssKu.css' %}">
    <title>My Website</title>
</head>
<body>
<nav class="navbar navbar-e xpand-lg navbar-light background-color: #fffff; ">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse navbar-center" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/profile">About Me</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/contact">Contact</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/schedule">My Schedule</a>
            </li>
        </ul>
    </div>
</nav>

<div class="row tulishana">
    <img src="{% static 'images/Desktop 5.png' %}">
</div>
<div class="row">
    <div class = "col-md-3 helo">
        <p>HELLO</p>
    </div>
    <div class = "col-md-3 you">
        <p>you<br>are</p>
    </div>
    <div class = "col-md-3 about">
        <p>about<br>to see</p>
    </div>
    <div class = "col-md-3 an">
        <p style="text-align:right">an <br>uninteractive</p>
    </div>
</div>

<div class="row">
    <div class = "col-md-6 resume">
        <p style="text-align:center">resume<br>of<br> me</p>
    </div>
    <div class= "col-md-3 photo">
        <img src="https://pbs.twimg.com/media/EDxkJeoVUAI5NA5.jpg" style="width:100%; height: 420px;">
    </div>
    <div class = "col-md-3 rec"></div>
</div>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

AppKu/templates/profile.html
<!doctype html>
<html lang="en">
{% load static %}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/cssKu.css' %}">
    <title>My Website</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light background-color: #fffff; ">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse navbar-center" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/profile">About Me</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/contact">Contact</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/schedule">My Schedule</a>
            </li>
        </ul>
    </div>
</nav>

<div class="row prof">
    <img src="{% static 'images/prof.png' %}">
</div>

<div class="row">
    <div class="col-md-12 desc">
        <p>Hi, my name is Hana. I’m a 18-year-old coder who is eager to learn new things. An<br>ENTP-T  person struggling with life.  I’m highly interested in technology and I love to<br>playing musical instruments.</p>
    </div>
</div>
<div class="row">
    <div class="col-md-12 blank"></div>
</div>
<div class="row">
    <div class="col-md-12 quote">
        <p>" It’s not whether you get knocked down, <br> it’s whether you get up."</p>
    </div>
</div>
<div class="row">
    <div class="col-md-12 vince">
        <p>Vince Lombardi</p>
    </div>
</div>
<div class="row edu">
    <img src="{% static 'images/edu.png' %}">
</div>

<div class="row">
    <div class="col-md- education">
        <p><br><br><br>
            • Faculty of Computer Science, <br>
            University of Indonesia <br> 2018 - now<br><br>
            • SMAN 5 Bogor <br> 2015 - 2018 <br><br>
            • SMPN 1 Bogor <br> 2012 - 2015<br><br>
            • SDN Polisi 4 Bogor <br> 2006 - 2014
        </p>
    </div>
    <div class="col-md-6 experience">
        <p><br><br><br>
            • Public Relations of RISTEK <br> 2019 - Present<br><br><br>
            • Member of ASEAN Youth Camp<br> 2016 - 2017<br><br>
            • Secretary of LIMIT 5 <br> 2015 – 2017<br><br>
            • Student Council of SMAN 5 Bogor <br> 2015 - 2016<br><br>
        </p>
        <button type="button" class="btn btn-secondary seemore" onclick="window.location.href='/seeMore'"> See More </button>
    </div>
</div>



<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

AppKu/templates/schedule.html
<!doctype html>
<html lang="en">
{% load static %}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/cssKu.css' %}">
    <title>My Website</title>
</head>
<body>
<br>
<nav class="navbar navbar-e xpand-lg navbar-light background-color: #fffff; ">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse navbar-center" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/profile">About Me</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/contact">Contact</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/schedule">My Schedule</a>
            </li>
        </ul>
    </div>
</nav>
<div class="row prof">
    <img src="{% static 'images/schedule.png' %}">
</div>
<div class="article">
    <a href="{% url 'AppKu:schedule' %}"></a>
    <div class="article">
        <div class="row">
            {% for schedule in schedules %}
            <div class="col-sm-4 text-center">
                <h2 style="font-family: 'Muli', sans-serif;">{{ schedule.activity }}</h2>
                <p   style="font-family: 'Muli', sans-serif;"> {{ schedule.date.date }}</p>
                <p   style="font-family: 'Muli', sans-serif;">{{ schedule.time}}</p>
                <p   style="font-family: 'Muli', sans-serif;">{{ schedule.place }}</p>
                <p   style="font-family: 'Muli', sans-serif;">{{ schedule.category }}</p>

                <div class = 'form-group'>
                    <form action="/schedule/clear/{{ schedule.id }}/" method="POST">
                        {% csrf_token %}
                        <button class="btn btn-danger" type="submit">Delete</button>
                    </form>
                </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
</br> </br> </br>
<div class = 'col-md-12'>
    <div class = 'form-group'>
        <a href="{% url 'AppKu:schedule_create' %}"><button type="button" class= "btn btn-secondary btn-lg btn-sm">Create</button></a>
    </div>
</div>
<div class="row">
    <div class = "col-md-3 one">
    </div>
    <div class = "col-md-3 two">
    </div>
    <div class = "col-md-3 three">
    </div>
    <div class = "col-md-3 four">
    </div>
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

AppKu/templates/schedule_create.html
<!doctype html>
<html lang="en">
{% load static %}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'css/cssKu.css' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>My Website</title>
</head>
<body>
<nav class="navbar navbar-e xpand-lg navbar-light background-color: #fffff; ">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse navbar-center" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/profile">About Me</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/contact">Contact</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/schedule">My Schedule</a>
            </li>
        </ul>
    </div>
</nav>
<form class="css" action="{% url 'AppKu:schedule_create' %}" method="post">
    {% csrf_token %}
    <div class="form-row">
        <div class="col-sm-1"></div>
        <div class="form-group col-sm-10">
            {% for fields in form %}
            {{ fields.label_tag }}
            <br>
            {{ fields }}
            {% endfor %}
        </div>
    </div>
    <div class="form-row">
        <div class="col-sm-1"></div>
        <input type="submit" class="btn btn-secondary float-right" value="Add">
</form>




<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

AppKu/templates/seeMore.html
<!doctype html>
<html lang="en">
{% load static %}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/cssKu.css' %}">
    <title>My Website</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light background-color: #fffff; ">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse navbar-center" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/profile">About Me</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/contact">Contact</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/schedule">My Schedule</a>
            </li>
        </ul>
    </div>
</nav>

<div class="row">
    <div class="col-md-12 blank"></div>
</div>
<div class="row comit">
    <img src="{% static 'images/comit.png' %}">
</div>
<div class="row">
    <div class="col-md-12 komite">
        <p><br><br><br>
            • PIC of Seminar Pekan Ristek 2019 <br>November 2019<br>
            (Tech even held by RISTEK)<br><br><br>
            • Liaison Officer staff of Open House Fasilkom<br>November 2019<br>
            (Event held by Fasilkom)<br><br><br>
            • Playground staff of Compfest 11 <br>September 2019<br>
            (Tech even held by Fasilkom)<br><br><br>
            • Liaison Officer staff of Wisuda Genap FASILKOM UI<br> August 2019<br>
            (Celebration and Ceremony for Fasilkom UI graduates)<br><br><br>
            • Decoration Division of Computer Get Together <br> February 2019<br>
            (Decorate all events on CGT)<br><br><br>
            • Seminar staff of Educare<br> Desember 2018<br>
            (Managed all seminar events on Educare)<br><br><br>
            • Public relations staff of Open House Fasilkom<br>September 2018<br>
            (Event held by Fasilkom)<br><br><br>
            • Public relations staff of Yearbook SMAN 5 Bogor<br>November 2017<br>
            (Coordinating all public relations activities of the yearbook)<br><br><br>
            • Marketing staff of DBL West Java <br> August 2017 <br>
            (Promoting and driving the sales of the Developmental Basketball League)<br><br><br>
        </p>
    </div>
</div>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>